In [ ]:
import pandas as pd
df = pd.read_csv("C:\\Formation\\capteurs_temperature.csv",sep=";",parse_dates=["timestamp"])
dfp = pd.read_csv("C:\\Formation\\capteurs_pression.tsv",sep="\t",parse_dates=["timestamp"])
# Compter les doublons
print(f"Nombre de doublons temperatures: {df.duplicated().sum()}")
print(f"Nombre de doublons pression: {dfp.duplicated().sum()}")
df.duplicated().unique()
dfp.duplicated().unique()
# Voir les lignes en doublon
# print("doublons temperatures:")
#print(df[df.duplicated(keep=False)])
#print("doublons pressions:")
#print(dfp[dfp.duplicated(keep=False)])
# types des colonnes
# print(df.dtypes)
print("infos temperatures:")
df.info()
print("infos pressions:")
dfp.info()

# Voir si une colonne contient des types mixtes
df.apply(lambda col: col.apply(type).unique())

# Convertir les types en chaînes de caractères avant value_counts()
# df.apply(lambda col: col.apply(type).astype(str).value_counts())

# Chercher les incohérences (valeurs qui ne correspondent pas au type)
for col in df.columns:
    types_uniques = df[col].apply(type).unique()
    if len(types_uniques) > 1:
        print(f"Incohérence dans '{col}': {types_uniques}")

# les valeurs extremes de date 
for col in df.select_dtypes(include='datetime').columns:
    print(col, df[col].min(), df[col].max()) 
# les valeurs extremes de date 
for col in dfp.select_dtypes(include='datetime').columns:
    print(col, dfp[col].min(), dfp[col].max())

for col in df.select_dtypes(include='number').columns:
    print(col)
    print(" temperature min:", df[col].min())
    print(" temperature max:", df[col].max())
for col in dfp.select_dtypes(include='number').columns:
    print(col)
    print(" pression min:", dfp[col].min())
    print(" pression max:", dfp[col].max())

# Obtenir la moyenne d'une colonne spécifique
moyennet = df['temperature'].mean()
print(f"moyenne des temperatures : {moyennet}")
moyennep = dfp['pressure_bar'].mean()
print(f"moyenne des pressions : {moyennep}")          

# Obtenir la médiane d'une colonne spécifique
medianet = df['temperature'].median()
print(f"mediane des temperatures : {medianet}")
medianep = dfp['pressure_bar'].median()
print(f"mediane des pressions : {medianep}")

# 1 Température et pression.
## 1.1 Chargement des fichiers de température et pression.
    conversion explicite des colonnes timestamp en datetime
## 1.2 informations générales pour chaque fichier
    Nombre de colonnes,leurs types, leurs noms, le nombre de lignes et le nombre de lignes non nulles dans chaque colonne.
    **Pour pression :**
    RangeIndex: 66800 entries, 0 to 66799
    Data columns (total 3 columns):
    #   Column        Non-Null Count  Dtype  
    ---  ------        --------------  -----  
    0   machine_id    65529 non-null  str    
    1   timestamp     65529 non-null  str    
    2   pressure_bar  65529 non-null  float64
    Malgré la conversion au chargement, le type de la colonne timestamp reste en str. Le format reste à investiguer (disparité)
    
    **Pour température : **
    RangeIndex: 66800 entries, 0 to 66799
    Data columns (total 3 columns):
    #   Column       Non-Null Count  Dtype         
    ---  ------       --------------  -----         
    0   machine_id   66800 non-null  str           
    1   timestamp    66800 non-null  datetime64[us]
    2   temperature  66668 non-null  float64 

## 1.3 les extrêmes
    Les min et max des dates et valeurs

    **Pour les températures :**
        date/heure min 2025-01-10 00:00:00, max 2026-12-02 23:00:00
        temperature min: 29.08
        temperature max: 135.3
    **Pour les pressions :**
        Il faut faire une correction sur le format pour avoir les min et max sur cette colonne
        pression min: 161.129
        pression max: 218.855
## 1.4 les doublons
    Nombre de doublons températures: 200
    Nombre de doublons pression: 131
## 1.5 les manques
    Il y a 132 valeurs manquantes dans le tableau de températures mais aucunes dans les pressions.
## 1.6 Les écarts
    La moyenne et médiane sont assez différentes pour les températures. Il y a sûrement des valeurs extrêmes à analyser de plus près.
        moyenne des températures : 53.31311663766724
        moyenne des pressions : 187.78798248103894
        mediane des températures : 40.87
        mediane des pressions : 186.496
    On peut demander au métier les raisons de cet écart de température (calibrage, panne, intervention de maintenance, etc).
    A ce stade, on ne peut pas prendre la décision de garder ou d'éliminer les valeurs extrêmes.

In [ ]:
import pandas as pd
df = pd.read_csv("C:\\Formation\\releves_incidents.csv",sep=",")
# création d'une colonne datetime à partir de date et heure
df['datetime'] = pd.to_datetime(df['date'] + ' ' + df['time'])
# infos
print("infos incidents :")

df.info()
# les min et max de temps
print(" date min: ", df["date"].min())
print(" date max: ", df["date"].max())

# Compter les doublons
print(f"Nombre de doublons incidents: {df.duplicated().sum()}")

# Nombre de valeurs distinctes
print("Nombre d'opérateurs: ",df['operator_name'].nunique())
print("Nombre de machines : ",df['machine_id'].nunique())

# 2 Chargement du fichier de d'incidents.
 Avec création d'une colonne supplémentaire pour concatener date et heure
## 2.1 informations générales 
    Nombre de colonnes,leurs types, leurs noms, le nombre de lignes et le nombre de lignes non nulles dans chaque colonne.
    RangeIndex: 283 entries, 0 to 282
    Data columns (total 9 columns):
    #   Column          Non-Null Count  Dtype
    ---  ------          --------------  -----
    0   incident_id     283 non-null    str  
    1   date            283 non-null    str  
    2   time            283 non-null    str  
    3   operator_name   280 non-null    str  
    4   machine_id      283 non-null    str  
    5   severity        283 non-null    int64
    6   operator_badge  280 non-null    str  
    7   comment         206 non-null    str  
    8   shift           283 non-null    str
    9   datetime        283 non-null    datetime64[us]  
    dtypes: datetime64[us](1),int64(1), str(8)
    On peut déjà remarquer que l'on a  des valeurs vides : opérateur nom et badge, commentaire.
    De plus, la colonne datetime a été crée pour permettre ensuite de potentiellement fusionner les 3 fichiers
## 2.2 les extrêmes
    Les min et max des dates
        date min: 2025-02-26
        date max: 2026-02-25
## 2.3 les doublons
    Nombre de doublons : 0
## 2.4 Nombre distinct de valeurs
- Nombre distinct de machines : 19
- Nombre distinct d'incidents : 282
- Nombre distinct d'opérateurs : 10

In [ ]:
import pandas as pd
# dfp = pd.read_csv("C:\\Formation\\capteurs_pression.tsv",sep="\t",parse_dates=["timestamp"])
dfp = pd.read_csv("C:\\Formation\\capteurs_pression.tsv",sep="\t")

# Essayer de convertir au format ISO (YYYY-MM-DD)
dfp['date_convertie'] = pd.to_datetime(dfp['timestamp'], format='%Y-%m-%d %H:%M:%S', errors='coerce')
#2025-09-01 03:00:00

# Créer des colonnes de diagnostic
dfp['est_valide'] = dfp['date_convertie'].notna()
# Générer un rapport
print("=" * 50)
print("RAPPORT DE VALIDATION DES DATES")
print("=" * 50)
print(f"Total de lignes: {len(dfp)}")
print(f"Dates valides: {dfp['est_valide'].sum()}")
print(f"Dates invalides: {(~dfp['est_valide']).sum()}")
print("\nLignes invalides détectées:")
print(dfp[~dfp['est_valide']][['timestamp']])

# Application du format uniforme sur toute la colonne
# dfp['date_convertie'] = dfp['timestamp'].dt.strftime('%Y-%m-%d %H:%M:%S')
dfp['est_valide'] = dfp['date_convertie'].notna()
# Générer un rapport
print("=" * 50)
print("RAPPORT DE VALIDATION DES DATES")
print("=" * 50)
print(f"Total de lignes: {len(dfp)}")
print(f"Dates valides: {dfp['est_valide'].sum()}")
print(f"Dates invalides: {(~dfp['est_valide']).sum()}")
print("\nLignes invalides détectées:")
print(dfp[~dfp['est_valide']][['timestamp']])

# Suppression des éventuelles lignes dont la date est invalide (NaT)
# dfp = dfp.dropna(subset=['timestamp'])

# Tri par date pour éviter des lignes brisées dans le désordre
# dfp = dfp.sort_values('timestamp')

# 3 Traitement des données
## 3.1 Traitement de transformation des dates
Il y a 262 dates invalides (non majoritaire).
Il faut donc transformer ces dates avec le format majoritaire qui est aussi celui des autres fichiers. Cela ouvrira le chemin un possible rapprochement des donnes entre les 3 fichiers (pression, temperatures, incidents).
## 3.2 homogénéisation des données
Mise à part les dates citées plus haut, il faut homogénéiser le nom des machines afin qu'elles puissent servir de pivot d'analyse.
## 3.3 visualisation des pression/temps
Un graphe permet d'analyser rapidement des données potentiellement anormales.
## 3.4 RGPD
Seule la colonne "operator_name" contient des informations personnelles. L'objectif étant la pévention des pannes, il peut être nécessaire de garder cette information mais de manière anonyme.
Je propose une anonymisation simple par remplacement ex : "marcel dupont" devient "op1", "laurent bruleau" devient "op2" ,etc. La donnée personnelle est protégée car mise à part l'association planning<-->nom de l'opérateur interne à la société, l'incident ne pourra pas rélier un opérateur à des incidents.

In [ ]:
import pandas as pd
# Homogénéisation des identifiants de machine
dft= pd.read_csv("C:\\Formation\\capteurs_temperature.csv",sep=";",parse_dates=["timestamp"])
dft['machine_id'] = dft['machine_id'].str.replace('MACH-', 'MACH_', regex=False)
dfi = pd.read_csv("C:\\Formation\\releves_incidents.csv",sep=",")
dfi['machine_id'] = dfi['machine_id'].str.replace('M-', 'MACH_', regex=False)
dfi['operator_name'] = dfi['operator_name'].str.replace('Nathan Richard', 'OP1', regex=False)

#2025-12-06T02:00:00+01:00
dfp = pd.read_csv("C:\\Formation\\capteurs_pression.tsv",sep="\t")
dfp['timestamp'] = dfp['timestamp'].str.replace('T', ' ', regex=False).str.replace('+01:00', '', regex=False)

# Affichage des premières lignes pour vérifier le changement
display(dft.head())
display(dfi.head())
display(dfp.head())

  machine_id           timestamp  temperature
0    MACH_01 2025-08-26 00:00:00        39.47
1    MACH_01 2025-08-26 01:00:00        38.25
2    MACH_01 2025-08-26 02:00:00        37.41
3    MACH_01 2025-08-26 03:00:00        37.66
4    MACH_01 2025-08-26 04:00:00        37.43

,incident_id,date,time,operator_name,machine_id,severity,operator_badge,comment,shift
0,INC-000192,2025-11-08,08:15,Nathan Richard,MACH_06,1,OP1006,vibration,matin
1,INC-000025,2025-04-12,13:20,Emma Dubois,MACH_10,1,OP1003,NaN,matin
2,INC-000123,2025-07-24,15:05,Jules Moreau,MACH_06,2,OP1010,bruit anormal,apres-midi
3,INC-000165,2025-09-25,14:00,Lina Petit,MACH_12,1,OP1007,alarme capteur,apres-midi
4,INC-000251,2026-01-05,16:10,Enzo Durand,MACH_3,1,OP1008,arrêt d'urgence,apres-midi

  machine_id            timestamp  pressure_bar
0    MACH_01  2025-08-26 00:00:00       195.687
1    MACH_01  2025-08-26 01:00:00       195.567
2    MACH_01  2025-08-26 02:00:00       196.608
3    MACH_01  2025-08-26 03:00:00       196.891
4    MACH_01  2025-08-26 04:00:00       196.308

# ORM
Génération d'un MCD à partir des 3 fichiers voir MCD.drawio.
Cela permet de générer un script sql de création de la base :

Voici un script SQL généré à partir du Modèle Conceptuel de Données (MCD) fourni dans les sources
. Ce script définit les tables, les colonnes, les types de données et les contraintes d'intégrité référentielle (clés étrangères).
-- Création de la table Machine
-- Table Machine
CREATE TABLE Machine (
    ID BIGINT PRIMARY KEY NOT NULL, -- PK long not null
    Nom VARCHAR(255) NOT NULL       -- string not null
);

-- Table Operateur
CREATE TABLE Operateur (
    ID BIGINT PRIMARY KEY NOT NULL, -- PK long not null
    Nom VARCHAR(255) NOT NULL       -- string not null
);

-- Table Capteur (Liée à Machine)
CREATE TABLE Capteur (
    ID BIGINT PRIMARY KEY NOT NULL, -- PK long not null
    Nom VARCHAR(255) NOT NULL,      -- string not null
    Type INTEGER NULL,              -- int null
    Unit VARCHAR(50) NULL,          -- string null
    Machine_ID BIGINT NOT NULL,
    CONSTRAINT fk_machine FOREIGN KEY (Machine_ID) REFERENCES Machine(ID)
);

-- Table Incident (Liée à Machine et Operateur)
-- Changement : Lien direct avec Machine 1 <-> 0..n [1]
CREATE TABLE Incident (
    ID BIGINT PRIMARY KEY NOT NULL,   -- PK long not null
    Date TIMESTAMP NOT NULL,          -- datetime not null
    severite SMALLINT NULL,           -- short null
    Commentaire TEXT NULL,            -- string null
    quarter SMALLINT NULL,            -- short null
    Machine_ID BIGINT NOT NULL,
    Operateur_ID BIGINT NOT NULL,
    CONSTRAINT fk_machine_incident FOREIGN KEY (Machine_ID) REFERENCES Machine(ID),
    CONSTRAINT fk_operateur_incident FOREIGN KEY (Operateur_ID) REFERENCES Operateur(ID)
);

-- Table Mesure (Liée à Capteur)
CREATE TABLE Mesure (
    ID BIGINT PRIMARY KEY NOT NULL,   -- PK long not null
    Valeur DOUBLE PRECISION NULL,     -- double null
    Date TIMESTAMP NULL,              -- datetime null
    Capteur_ID BIGINT NOT NULL,
    CONSTRAINT fk_capteur_mesure FOREIGN KEY (Capteur_ID) REFERENCES Capteur(ID)
);
Détails de l'implémentation basés sur le MCD
 :
Clés Primaires (PK) : Toutes les entités possèdent un identifiant de type long (traduit ici par BIGINT)
.
Gestion des relations :
La table Capteur inclut une clé étrangère vers Machine car une machine peut posséder plusieurs capteurs
.
La table Incident intègre des clés étrangères vers Operateur et Machine pour refléter les liens hiérarchiques et d'association définis dans le schéma
.
La table Mesure est rattachée au Capteur correspondant
.
Types de données : Les types string, int, short, double et datetime ont été convertis vers leurs équivalents SQL standards (VARCHAR, INTEGER, SMALLINT, DOUBLE PRECISION, TIMESTAMP)

In [7]:
from sqlalchemy import create_engine, Column, Integer, BigInteger, String, Float, DateTime, ForeignKey, SmallInteger, Text
from sqlalchemy.orm import declarative_base, relationship, sessionmaker

Base = declarative_base()

class Machine(Base):
    __tablename__ = 'machine'
    id = Column(BigInteger, primary_key=True) # ID (PK long not null) [1]
    nom = Column(String, nullable=False)      # Nom (string not null) [1]
    
    capteurs = relationship("Capteur", back_populates="machine")
    incidents = relationship("Incident", back_populates="machine") # Nouveau lien [1]

class Operateur(Base):
    __tablename__ = 'operateur'
    id = Column(BigInteger, primary_key=True)
    nom = Column(String, nullable=False)
    incidents = relationship("Incident", back_populates="operateur")

class Capteur(Base):
    __tablename__ = 'capteur'
    id = Column(BigInteger, primary_key=True)
    nom = Column(String, nullable=False)
    type = Column(Integer)
    unit = Column(String)
    machine_id = Column(BigInteger, ForeignKey('machine.id'), nullable=False)
    
    machine = relationship("Machine", back_populates="capteurs")
    mesures = relationship("Mesure", back_populates="capteur")

class Incident(Base):
    __tablename__ = 'incident'
    id = Column(BigInteger, primary_key=True)
    date = Column(DateTime, nullable=False)    # Date (datetime not null) [1]
    severite = Column(SmallInteger)            # severite (short null) [1]
    commentaire = Column(Text)                 # Commentaire (string null) [1]
    quarter = Column(SmallInteger)             # quarter (short null) [1]
    
    # Relations d'après le nouveau schéma [1]
    machine_id = Column(BigInteger, ForeignKey('machine.id'), nullable=False)
    operateur_id = Column(BigInteger, ForeignKey('operateur.id'), nullable=False)
    
    machine = relationship("Machine", back_populates="incidents")
    operateur = relationship("Operateur", back_populates="incidents")

class Mesure(Base):
    __tablename__ = 'mesure'
    id = Column(BigInteger, primary_key=True)
    valeur = Column(Float)                     # Valeur (double null) [1]
    date = Column(DateTime)                    # Date (datetime null) [1]
    capteur_id = Column(BigInteger, ForeignKey('capteur.id'), nullable=False)
    
    capteur = relationship("Capteur", back_populates="mesures")

# Connexion à la base de données (exemple avec SQLite pour le test)
# engine = create_engine('sqlite:///indusense.db')

# --- CONNEXION POSTGRESQL DANS DOCKER ---

# Remplacez par vos identifiants Docker
USER = "myuser"
PASSWORD = "mypassword"
HOST = "localhost" # Ou le nom du service si le script est aussi dans Docker
PORT = "5432"
DB_NAME = "mydb"

DATABASE_URL = f"postgresql://{USER}:{PASSWORD}@{HOST}:{PORT}/{DB_NAME}"

engine = create_engine(DATABASE_URL)
# engine = create_engine("postgresql+psycopg://dbuser:dbpassword@localhost:5432/mydb")
# Création des tables dans PostgreSQL
Base.metadata.create_all(engine)